import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "@mantine/core/styles.css";
import "@mantine/notifications/styles.css";

import { MantineProvider, createTheme } from "@mantine/core";
import { Notifications } from "@mantine/notifications";
import { AuthProvider } from "./providers/authContext";
import { ExchangeProvider } from "./providers/exchangeContext";

const inter = Inter({ subsets: ["latin"] });

const theme = createTheme({});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MantineProvider theme={theme}>
          <AuthProvider>
            <ExchangeProvider>
              <Notifications />
              {children}
            </ExchangeProvider>
          </AuthProvider>
        </MantineProvider>
      </body>
    </html>
  );
}
